// <auto-generated />
namespace G4S.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class flocid_correct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(flocid_correct));
        
        string IMigrationMetadata.Id
        {
            get { return "201705221845157_flocid_correct"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
