// <auto-generated />
namespace G4S.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class LoginLicense_required : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LoginLicense_required));
        
        string IMigrationMetadata.Id
        {
            get { return "201705201114559_LoginLicense_required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
